# New Docker Compose format (since 9-2020)
name: dsmrsql

services:
  app:
    build: .
    environment:
      DSMR_DB_NAME: dsmr
      DSMR_DB_USER: dsmr
      DSMR_DB_PASSWORD: dsmr
      DSMR_DB_HOST: db
      DSMR_DEVICE: /dev/ttyUSB0
      # Choices: V2_2, V4, V5 (for V3, use V2_2)
      DSMR_SERIAL_SETTINGS: V5
      # Choices: V2_2, V3, V4, V5
      DSMR_TELEGRAM_SPECIFICATION: V5
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: dsmr
      POSTGRES_PASSWORD: dsmr
      POSTGRES_DB: dsmr
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - 44757:3000
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped

volumes:
  db:
  grafana:
