{
 "title": "Energy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Meter readings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  electricity_used_tariff_1+electricity_used_tariff_2 AS \"Used\",\n  electricity_delivered_tariff_1+electricity_delivered_tariff_2 AS \"Delivered\"\nFROM dsmrsql_telegram\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Instantaneous Energy Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  (CASE WHEN (electricity_used_tariff_1+electricity_used_tariff_2)*3600 >= lag((electricity_used_tariff_1+electricity_used_tariff_2)*3600) OVER (ORDER BY time) THEN (electricity_used_tariff_1+electricity_used_tariff_2)*3600 - lag((electricity_used_tariff_1+electricity_used_tariff_2)*3600) OVER (ORDER BY time) WHEN lag((electricity_used_tariff_1+electricity_used_tariff_2)*3600) OVER (ORDER BY time) IS NULL THEN NULL ELSE (electricity_used_tariff_1+electricity_used_tariff_2)*3600 END)/extract(epoch from time - lag(time) OVER (ORDER BY time)) AS \"Used\",\n  (CASE WHEN (electricity_delivered_tariff_1+electricity_delivered_tariff_2)*3600 >= lag((electricity_delivered_tariff_1+electricity_delivered_tariff_2)*3600) OVER (ORDER BY time) THEN (electricity_delivered_tariff_1+electricity_delivered_tariff_2)*3600 - lag((electricity_delivered_tariff_1+electricity_delivered_tariff_2)*3600) OVER (ORDER BY time) WHEN lag((electricity_delivered_tariff_1+electricity_delivered_tariff_2)*3600) OVER (ORDER BY time) IS NULL THEN NULL ELSE (electricity_delivered_tariff_1+electricity_delivered_tariff_2)*3600 END)/extract(epoch from time - lag(time) OVER (ORDER BY time)) AS \"Delivered\"\nFROM dsmrsql_telegram\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last Telegram",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  time AS \"telegram_time\"\nFROM dsmrsql_telegram\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last telegram",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  raw\nFROM dsmrsql_telegram\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Historic Instantaneous",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM dsmrsql_telegram\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  }
 ]
}