# Generated by Django 4.0.6 on 2022-07-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('raw', models.TextField()),
                ('electricity_used_tariff_1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('electricity_used_tariff_2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('electricity_delivered_tariff_1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('electricity_delivered_tariff_2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('electricity_active_tariff', models.CharField(max_length=100)),
                ('current_electricity_usage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_electricity_delivery', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gas_meter_time', models.DateTimeField()),
                ('gas_meter_reading', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
