# Generated by Django 4.0.6 on 2022-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('used_1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('used_2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('delivered_1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('delivered_2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('current_usage', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('current_delivery', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramRaw',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('telegram', models.TextField()),
            ],
        ),
    ]
